apiVersion: v1
kind: Service
metadata:
  name: {{ include "telemetry.fullname" . }}-mq
  labels:
    app: {{ include "telemetry.name" . }}
    component: mq
spec:
  type: ClusterIP
  selector:
    app: {{ include "telemetry.name" . }}
    component: mq
  ports:
    - name: http
      port: {{ .Values.mq.servicePort }}
      targetPort: http