apiVersion: v1
kind: Secret
metadata:
  name: telemetry-postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: telemetry
  POSTGRES_PASSWORD: telemetry
  POSTGRES_DB: telemetry
  POSTGRES_DSN: postgresql://telemetry:telemetry@telemetry-postgres:5432/telemetry?sslmode=disable